WebShopping/WebShopping/Controllers/CartController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using WebShopping.Models;

namespace WebShopping.Controllers
{
    public class CartController : Controller
    {
        private ShopContext db = new ShopContext();
        private const string CartSession = "CartSession";
        // GET: Cart
        public ActionResult Index()
        {
            var cart = Session[CartSession];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }
            return View(list);
        }
        public ActionResult AddItem(long productId, int quantity)
        {
            var product = db.Product.Find(productId);
            var cart = Session[CartSession];
            if (cart != null)
            {
                var list = (List<CartItem>)cart;
                if (list.Exists(x => x.Product.ProductID == productId))
                {

                    foreach (var item in list)
                    {
                        if (item.Product.ProductID == productId)
                        {
                            item.Quantity += quantity;
                        }
                    }
                }
                else
                {
                    //tạo mới đối tượng cart item
                    var item = new CartItem();
                    item.Product = product;
                    item.Quantity = quantity;
                    list.Add(item);
                }
                //Gán vào session
                Session[CartSession] = list;
            }
            else
            {
                //tạo mới đối tượng cart item
                var item = new CartItem();
                item.Product = product;
                item.Quantity = quantity;
                var list = new List<CartItem>();
                list.Add(item);
                //Gán vào session
                Session[CartSession] = list;
            }
            return RedirectToAction("Index");
        }
        public ActionResult Update(FormCollection form )
        {
            int productId = int.Parse(form["ProductID"]);
            int Q_ty = int.Parse(form["Quantity"]);

            //var product = db.Product.Find(productId);
            var cart = Session[CartSession];

            var list = (List<CartItem>)cart;
            if (list.Exists(x => x.Product.ProductID == productId))
            {

                foreach (var item in list)
                {
                    if (item.Product.ProductID == productId)
                    {
                        item.Quantity = Q_ty;
                    }
                }
            }

            return RedirectToAction("Index");
        }
        public ActionResult DeleteAll()
        {
            //Session[CartSession] = null;
            //var list = new List<CartItem>();
            //return View("Index", list);

            var cart = Session[CartSession];
            var list = (List<CartItem>)cart;
            list.Clear();
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int productId)
        {            
            var cart = Session[CartSession];
            var list = (List<CartItem>)cart;

            list.RemoveAll(s=>s.Product.ProductID== productId);

            return RedirectToAction("Index");
        }

        public PartialViewResult BagCart()
        {
            int _item = 0;
            var cart = Session[CartSession];
            if (cart!=null)
            {
                var list = (List<CartItem>)cart;
                _item = list.Sum(s => s.Quantity);
            }            
            ViewBag.infoCart = _item;
            return PartialView("BagCart");
        }
        [Authorize]
        public ActionResult Checkout()
        {
            //string UserID = User.Identity.GetUserId();
            //string UserName = User.Identity.GetUserName();  
            ViewBag.UserName = User.Identity.GetUserName();
            return View();
        }
        [HttpPost]
        public ActionResult Checkout(FormCollection form)
        {
            try
            {
                //check Customer                
                string Email = User.Identity.GetUserName();
                int Customer_ID = 0;
                var Cus = from s in db.Customer
                               select s;
                var C_user = Cus.Where(s => s.Email == Email).ToList();            
                if (C_user.Count()>0)
                {
                    Customer_ID = C_user[0].ID;

                }
                else
                {
                    //Create Customer "ID,Name,Address,Phone,Email"
                    Customer customer = new Customer();
                    customer.Name = Email;
                    customer.Address = form["Ship_Address"];
                    customer.Phone = form["Phone"];
                    customer.Email = Email;
                    db.Customer.Add(customer);
                    Customer_ID = customer.ID;
                    //db.SaveChanges();
                }

                //Create Order "ID,CustomerID,OrderDate,RequreDate,ShipAddress,Phone"
                Order OrderItem = new Order();
                OrderItem.CustomerID = Customer_ID;
                OrderItem.OrderDate = DateTime.Now;
                OrderItem.RequreDate = DateTime.Parse(form["Requre_Date"]);
                OrderItem.ShipAddress = form["Ship_Address"];
                OrderItem.Phone = form["Phone"];
                db.Order.Add(OrderItem);
                //db.SaveChanges();
                //Create OrderDetail "OrderID,ProductID,Quantity,UnitPrice"
                var cart = Session[CartSession];
                var list = (List<CartItem>)cart;
                foreach (var item in list)
                {
                    OrderDetail orderDetail = new OrderDetail();
                    orderDetail.OrderID = OrderItem.ID;
                    orderDetail.ProductID = item.Product.ProductID;
                    orderDetail.Quantity = item.Quantity;
                    orderDetail.UnitPrice = item.Product.UnitPrice;
                    db.OrderDetail.Add(orderDetail);
                }
                db.SaveChanges();
                //Delete All Cart
                list.Clear();
                return View("Checkout_Success");
            }
            catch
            {
                return Content("Error Checkout. Kiểm tra lại thông tin");
                
            }
            
        }
    }
}

WebShopping/WebShopping/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebShopping.Models;

namespace WebShopping.Controllers
{
    public class CustomersController : Controller
    {
        private ShopContext db = new ShopContext();

        // GET: Customers
        public ActionResult Index()
        {
            return View(db.Customer.ToList());
        }

        // GET: Customers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customer.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: Customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Address,Phone,Email")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Customer.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customer);
        }

        // GET: Customers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customer.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Address,Phone,Email")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customer.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = db.Customer.Find(id);
            db.Customer.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebShopping/WebShopping/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebShopping.Models;

namespace WebShopping.Controllers
{
    public class OrdersController : Controller
    {
        private ShopContext db = new ShopContext();

        // GET: Orders
        public ActionResult Index()
        {
            var order = db.Order.Include(o => o.Customer);
            return View(order.ToList());
        }

        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Order.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
            ViewBag.CustomerID = new SelectList(db.Customer, "ID", "Name");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,CustomerID,OrderDate,RequreDate,ShipAddress,Phone")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Order.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CustomerID = new SelectList(db.Customer, "ID", "Name", order.CustomerID);
            return View(order);
        }

        // GET: Orders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Order.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewBag.CustomerID = new SelectList(db.Customer, "ID", "Name", order.CustomerID);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,CustomerID,OrderDate,RequreDate,ShipAddress,Phone")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CustomerID = new SelectList(db.Customer, "ID", "Name", order.CustomerID);
            return View(order);
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Order.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Order.Find(id);
            db.Order.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebShopping/WebShopping/Controllers/RolesController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebShopping.Models;

namespace WADReview.Controllers
{
    [Authorize(Roles ="admin")]
    public class RoleController : Controller
    {
        // GET: Roles
        private ApplicationDbContext context = new ApplicationDbContext();

        public ActionResult Index()
        {
            var Roles = context.Roles.ToList();
            //            return View();
            return View(Roles);
            //            return View("ViewName");
            //            return View("ViewName",Roles);
        }
        [HttpGet]
        public ActionResult AddUserToRole()
        {
            using (var context = new ApplicationDbContext())
            {
                var users = from u in context.Users
                            select u;
                // ViewBag.Users = new SelectList(users, "Id", "UserName");
                ViewBag.UserName = users.Select(x => new SelectListItem { Text = x.UserName, Value = x.Id }).ToList();
                var roles = from r in context.Roles
                            select r;
                ViewBag.Name = roles.Select(x => new SelectListItem { Text = x.Name, Value = x.Name }).ToList();
            }
            return View();
        }
        [HttpPost]
        public ActionResult AddUserToRole(string UserName, string Name)
        {
            //var context = new AccountController();
            var context = new ApplicationDbContext();

            //var roleStore = new RoleStore<IdentityRole>(context);
            //var roleManager = new RoleManager<IdentityRole>(roleStore);

            var userStore = new UserStore<ApplicationUser>(context);
            var userManager = new UserManager<ApplicationUser>(userStore);
            userManager.AddToRole(UserName, Name);

            //userManager.AddToRole(UserName, Name);

            ViewBag.Name = UserName;
            ViewBag.Role = Name;
            return View("AddConfirm");
        }

        public ActionResult Create()
        {
            var Role = new IdentityRole();
            return View(Role);
        }
        [HttpPost]
        public ActionResult Create(IdentityRole Role)
        {
            context.Roles.Add(Role);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebShopping/WebShopping/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebShopping/WebShopping/Views/Shared/_LayoutTemplate.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/Asset/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="/Asset/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="/Asset/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="/Asset/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/Asset/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="/Asset/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="/Asset/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="/Asset/plugins/summernote/summernote-bs4.min.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("CSS", required: false)
    
</head>
<body class="hold-transition sidebar-mini layout-navbar-fixed layout-fixed">
    <div class="wrapper">
        <!-- Main Header Container -->
        <div>
            @RenderPage("~/Views/Shared/_PartialHeader.cshtml")
        </div>
        <!-- Main Sidebar Container -->
        <div>
            @RenderPage("~/Views/Shared/_PartialSidebar.cshtml")
        </div>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <div>
                @RenderBody()
            </div>
        </div>
    </div>
    <!--Footer content-->>
    <div>
        <footer class="main-footer">
            <strong>Copyright &copy; 2014-2020 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
            All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                <b>Version</b> 3.1.0-rc
            </div>
        </footer>
    </div>
    <!-- jQuery -->
    <script src="/Asset/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="/Asset/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>$.widget.bridge('uibutton', $.ui.button)</script>
    <!-- Bootstrap 4 -->
    <script src="/Asset/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- ChartJS -->
    <script src="/Asset/plugins/chart.js/Chart.min.js"></script>
    <!-- Sparkline -->
    <script src="/Asset/plugins/sparklines/sparkline.js"></script>
    <!-- JQVMap -->
    <script src="/Asset/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="/Asset/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="/Asset/plugins/jquery-knob/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="/Asset/plugins/moment/moment.min.js"></script>
    <script src="/Asset/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="/Asset/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="/Asset/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="/Asset/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/Asset/dist/js/adminlte.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/Asset/dist/js/demo.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="/Asset/dist/js/pages/dashboard.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")    
    @RenderSection("scripts", required: false)
</body>
</html>

WebShopping/WebShopping/Views/Shared/_PartialHeader.cshtml
<!-- Main Header Container -->
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Home" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Home/Contact" class="nav-link">Contact</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Home/About" class="nav-link">About</a>
        </li>

    </ul>


    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">

        @Html.Action("BagCart","Cart")
        @Html.Partial("_LoginPartial")
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link"></a>
        </li>
    </ul>
    

</nav>
    <!-- /.navbar -->

WebShopping/WebShopping/Views/Shared/_PartialSidebar.cshtml
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="/Home" class="brand-link elevation-4">
        <img src="/Asset/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">Web Shopping</span>
    </a>
    <div class="sidebar">
        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
    with font-awesome or any other icon font library -->
                @if (User.IsInRole("admin"))
                {
                    <li class="nav-item">
                        <a href="#" class="nav-link active">
                            <i class="nav-icon fas fa-tachometer-alt"></i>
                            <p>
                                Admin
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview" style="display: none;">
                            <li class="nav-item">
                                <a href="@Url.Action("Index","Role")" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Role</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("Index","Customers")" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Customers</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("Index","Orders")" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Orders</p>
                                </a>
                            </li>

                            <li class="nav-item">
                                <a href="@Url.Action("Index","OrderDetails")" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>OrderDetails</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("Index","Products")" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Products</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("Index","Categories")" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Categories</p>
                                </a>
                            </li>

                        </ul>
                    </li>

                }       

                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-file"></i>
                        <p>...</p>
                    </a>
                </li>
                
               

            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>

</aside>